# -*- coding: utf-8 -*-
"""PBDB_Stats (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKNLxjcCcSn54llJBZOetLwLO_C-V1k_
"""

import pandas as pd
import numpy as np

"""# Prepare Stats"""

def clean_df(df):
    if "Last" in df.columns and "First" in df.columns:
        # Normalize all blank or 'nan' text entries to proper NaN
        df["Last"] = df["Last"].astype(str).str.strip()
        df["First"] = df["First"].astype(str).str.strip()

        df["Last"].replace(["", "nan", "NaN", "None"], np.nan, inplace=True)
        df["First"].replace(["", "nan", "NaN", "None"], np.nan, inplace=True)

        # Find and drop the first totals or empty row (and anything after it)
        totals_idx = df.index[df["Last"].isna() & df["First"].isna()]
        if len(totals_idx) > 0:
            first_total = totals_idx[0]
            df = df.loc[:first_total - 1].reset_index(drop=True)

    return df

def prepare_batting_stats(df):
    df = df.copy()

    columns_to_keep = [
    "Last", "First",
    "PA", "AB", "H", "AVG", "OBP", "SLG", "OPS", "RBI", "R",
    "BB", "SO", "XBH" "2B", "3B","HR", "TB", "SB",
    "PS/PA", "BB/K", "C%",
    "QAB", "QAB%", "HHB", "HHB %",
    "LD%", "FB%", "GB%",
    "BABIP", "BA/RISP", "2OUTRBI"
]

    existing_columns = [col for col in columns_to_keep if col in df.columns]
    df = df[existing_columns].copy()

    if "PA" in df.columns:
        df["PA"] = pd.to_numeric(df["PA"], errors="coerce")
        before_drop = len(df)
        df = df[df["PA"] != 0].reset_index(drop=True)
        dropped = before_drop - len(df)


    # Sort alphabetically by Last, then First
    if "Last" in df.columns and "First" in df.columns:
        df = df.sort_values(by=["Last", "First"], ascending=[True, True]).reset_index(drop=True)


    return df

def prepare_pitching_stats(df):
    df = df.copy()

    columns_to_keep = [
    "Last", "First",
    "IP", "ERA", "WHIP", "H", "R", "ER", "BB", "BB/INN", "SO", "K-L", "HR",
    "S%", "FPS%", "FPSO%", "FPSH%", "SM%", "<3%",
    "LD%", "FB%", "GB%", "HHB%", "WEAK%", "BBS",
    "BAA", "BABIP", "BA/RISP",
    "CS", "SB", "SB%",
    "FIP"
]

    existing_columns = [col for col in columns_to_keep if col in df.columns]
    df = df[existing_columns].copy()

    if "IP" in df.columns:
        df["IP"] = pd.to_numeric(df["IP"], errors="coerce")
        before_drop = len(df)
        df = df[df["IP"] != 0].reset_index(drop=True)
        dropped = before_drop - len(df)


    for col in df.columns:
      if col not in ["Last", "First", "BABIP", "BAA", "BA/RISP"]:
          if pd.api.types.is_numeric_dtype(df[col]):
              df[col] = df[col].round(2)


    # Sort alphabetically by Last, then First
    if "Last" in df.columns and "First" in df.columns:
        df = df.sort_values(by=["Last", "First"], ascending=[True, True]).reset_index(drop=True)



    return df

def prepare_fielding_stats(df):
    df = df.copy()

    columns_to_keep = ["Last", "First", "TC", "A", "PO", "FPCT", "E", "DP"]

    existing_columns = [col for col in columns_to_keep if col in df.columns]
    df = df[existing_columns].copy()

    if "TC" in df.columns:
        df["TC"] = pd.to_numeric(df["TC"], errors="coerce")
        before_drop = len(df)
        df = df[df["TC"] != 0].reset_index(drop=True)
        dropped = before_drop - len(df)


     # Sort alphabetically by Last, then First
    if "Last" in df.columns and "First" in df.columns:
        df = df.sort_values(by=["Last", "First"], ascending=[True, True]).reset_index(drop=True)


    for col in df.columns:
        if col not in ["Last", "First","FPCT"]:
            if pd.api.types.is_numeric_dtype(df[col]):
                df[col] = df[col].round(0)
    return df

def prepare_catching_stats(df):
    df = df.copy()

    columns_to_keep = ["Last", "First", "INN", "PB", "SB-ATT", "CS", "CS%"]

    existing_columns = [col for col in columns_to_keep if col in df.columns]
    df = df[existing_columns].copy()

    if "INN" in df.columns:
        df["INN"] = pd.to_numeric(df["INN"], errors="coerce")
        before_drop = len(df)
        df = df[df["INN"] != 0].reset_index(drop=True)
        dropped = before_drop - len(df)

    return df

def filter_by_player(player_list, df):
  if 'Last' not in df.columns:
        raise ValueError("DataFrame must contain a 'Last' column.")

  return df[df['Last'].isin(player_list)].copy()

#def add_totals_row_hitting(df):

"""
# Aggregation (Pitching)"""

def aggregate_stats_pitching(csv_files):
    # Base numeric columns needed for calculations
    cols_to_keep = [
        "IP", "ER", "H", "BB", "R", "SO", "K-L", "HR", "#P", "BF", "HBP",
        "FPS%", "FPSO%", "FPSW%", "FPSH%", "S%", "SM%", "LD%", "FB%", "GB%",
        "BABIP", "BA/RISP", "CS", "SB", "SB%", "<3%", "HHB%", "WEAK%", "BBS"
    ]

    dfs = []
    for name in csv_files:
        file = f"{name}.csv"
        df = pd.read_csv(file, header=1)  # use header=1 only if CSV has two header lines
        df = df.iloc[:, [1, 2] + list(range(53, 148))]
        df.columns = [c.replace(".1", "") for c in df.columns]

        # Ensure name columns exist and keep only relevant columns
        if 'Last' not in df.columns:
                df['Last'] = ""
        if 'First' not in df.columns:
                df['First'] = ""

        # Keep only relevant columns that exist
        df = df[[c for c in cols_to_keep + ["Last", "First"] if c in df.columns]]


        # Clean names
        df["Last"] = df["Last"].astype(str).str.strip().str.title()
        df["First"] = df["First"].astype(str).str.strip().str.title()

        # Convert numeric columns
        for col in df.columns:
            if col not in ["Last", "First"]:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

 # --- Convert innings format (e.g., 4.2 → 4.6667) ---
        def convert_innings(ip):
            whole = int(ip)
            fraction = round((ip - whole) * 10)
            if fraction == 1:
                return whole + 1/3
            elif fraction == 2:
                return whole + 2/3
            else:
                return ip

        if "IP" in df.columns:
            df["IP"] = df["IP"].apply(convert_innings)


        # ===== Convert percentages to absolute counts =====
        df["Strikes"] = (df["S%"] * df["#P"] / 100).round(0).astype(int)
        df["FirstPitchStrikes"] = (df["FPS%"] * df["BF"] / 100).round(0).astype(int)
        df["FPSO"] = (df["FPSO%"] * df["BF"] / 100).round(0).astype(int)
        df["FPSH"] = (df["FPSH%"] * df["BF"] / 100).round(0).astype(int)

        total_batted_balls = df["BF"] - df["SO"] - df["BB"] - df["HBP"]
        df["GroundBalls"] = (df["GB%"] * total_batted_balls / 100).round(0).astype(int)
        df["FlyBalls"] = (df["FB%"] * total_batted_balls / 100).round(0).astype(int)
        df["LineDrives"] = (df["LD%"] * total_batted_balls / 100).round(0).astype(int)
        df["HardHitBalls"] = (df["HHB%"] * total_batted_balls / 100).round(0).astype(int)
        df["WeakContact"] = (df["WEAK%"] * total_batted_balls / 100).round(0).astype(int)
        df["Under3Pitches"] = (df["<3%"] * df["BF"] / 100).round(0).astype(int)
        df["SwingMisses"] = (df["SM%"] * df["#P"] / 100).round(0).astype(int)

        # Drop original % columns to avoid confusion in later aggregation
        drop_cols = [c for c in df.columns if c.endswith("%")]
        df.drop(columns=drop_cols, inplace=True, errors='ignore')

        dfs.append(df)

    # ===== Combine and aggregate by player =====
    combined = pd.concat(dfs, ignore_index=True)

    # Group by player and sum all numeric values
    agg_df = (
        combined.groupby(["Last", "First"], as_index=False)
        .sum(numeric_only=True)
    )
    # Convert all numeric columns to integers, handling potential NaNs resulting from sum
    for col in agg_df.columns:
        if col not in ["Last", "First"]:
            agg_df[col] = agg_df[col].fillna(0).round(3)


    return agg_df

def generate_aggregated_pitching_df(df):

    columns_to_keep = [
        "Last", "First", "IP", "ERA", "WHIP", "SO", "K-L", "H", "R", "ER", "BB", "BB/INN",
        "FIP", "S%", "FPS%", "FPSO%", "FPSH%", "BAA", "BBS", "SM%", "LD%", "FB%", "GB%",
        "BABIP", "BA/RISP", "CS", "SB", "SB%", "<3%", "HHB%", "WEAK%"
    ]

    df = df.copy()

    # ==== Safety checks ====
    for col in [
        "IP", "ER", "H", "BB", "SO", "K-L", "HR", "#P", "BF", "Strikes", "FirstPitchStrikes",
        "FPSO", "FPSH", "GroundBalls", "FlyBalls", "LineDrives", "HardHitBalls", "WeakContact",
        "Under3Pitches", "SwingMisses", "BBS", "CS", "SB"
    ]:
        if col not in df.columns:
            df[col] = 0

    # Avoid divide-by-zero
    df["IP"] = df["IP"].replace(0, np.nan)
    df["BF"] = df["BF"].replace(0, np.nan)
    df["#P"] = df["#P"].replace(0, np.nan)

    # ==== Derived metrics ====

    # ERA = (ER × 9) / IP
    df["ERA"] = (df["ER"] * 9 / df["IP"]).round(2)

    # WHIP = (BB + H) / IP
    df["WHIP"] = ((df["BB"] + df["H"]) / df["IP"]).round(2)

    # BB/INN = BB / IP
    df["BB/INN"] = (df["BB"] / df["IP"]).round(2)

    # FIP = ((13*HR + 3*BB - 2*K) / IP) + constant
    # Standard constant = 3.1 for normalization
    df["FIP"] = (((13 * df["HR"]) + (3 * df["BB"]) - (2 * df["SO"])) / df["IP"] + 3.1).round(2)

    # Percentages
    df["S%"] = (df["Strikes"] / df["#P"] * 100).round(2)
    df["FPS%"] = (df["FirstPitchStrikes"] / df["BF"] * 100).round(2)
    df["FPSO%"] = (df["FPSO"] / df["BF"] * 100).round(2)
    df["FPSH%"] = (df["FPSH"] / df["BF"] * 100).round(2)
    df["SM%"] = (df["SwingMisses"] / df["#P"] * 100).round(2)
    df["LD%"] = (df["LineDrives"] / (df["BF"]-df["SO"]-df["BB"]-df["HBP"]) * 100).round(2)
    df["FB%"] = (df["FlyBalls"] / (df["BF"]-df["SO"]-df["BB"]-df["HBP"]) * 100).round(2)
    df["GB%"] = (df["GroundBalls"] / (df["BF"]-df["SO"]-df["BB"]-df["HBP"]) * 100).round(2)
    df["HHB%"] = (df["HardHitBalls"] / (df["BF"]-df["SO"]-df["BB"]-df["HBP"]) * 100).round(2)
    df["WEAK%"] = (df["WeakContact"] / (df["BF"]-df["SO"]-df["BB"]-df["HBP"]) * 100).round(2)
    df["<3%"] = (df["Under3Pitches"] / df["BF"] * 100).round(2)

    # SB%
    df["SB%"] = np.where(
        (df["SB"] + df["CS"]) > 0,
        (df["SB"] / (df["SB"] + df["CS"]) * 100).round(1),
        0
    )

    # BAA = H / (BF - BB - HBP)
    df["BAA"] = np.where(
        (df["BF"] - df["BB"] - df["HBP"]) > 0,
        (df["H"] / (df["BF"] - df["BB"] - df["HBP"])).round(3),
        0
    )

    # BABIP = (H - HR) / (BF - K - HR - BB - HBP)
    df["BABIP"] = np.where(
        (df["BF"] - df["SO"] - df["HR"] - df["BB"] - df["HBP"]) > 0,
        ((df["H"] - df["HR"]) / (df["BF"] - df["SO"] - df["HR"] - df["BB"] - df["HBP"])).round(3),
        0
    )

    # BA/RISP: leave as 0 unless calculated separately from another dataset
    if "BA/RISP" not in df.columns:
        df["BA/RISP"] = 0.000

    # Reformat column names and fill missing ones
    for col in columns_to_keep:
        if col not in df.columns:
            df[col] = 0

    # ==== Final cleanup ====
    df = df[columns_to_keep].copy()
    df = df.round(3)
    df = df.fillna(0)

    return df

pitching_df = aggregate_stats_pitching(["wake","jmu"])

pitching_df = generate_aggregated_pitching_df(pitching_df)
pitching_df = prepare_pitching_stats(pitching_df)
pitching_df.head()

"""
# Aggregation (Hitting)"""

def aggregate_stats_hitting(csv_files):
    cols_to_keep = [
        "Last", "First",
        "PA", "AB", "H", "BB", "HBP", "SF",
        "TB", "R", "RBI", "SO",
        "2B", "3B", "HR", "SB", "CS",
        "QAB", "HHB",
        "LD", "FB", "GB",
        "H_RISP", "AB_RISP",
        "PS", "2OUTRBI", "XBH"
    ]

    dfs = []
    for name in csv_files:
        file = f"{name}.csv"
        df = pd.read_csv(file, header=1)  # use header=1 only if your CSV has two header lines
        df = df[[c for c in cols_to_keep if c in df.columns]]

        # Clean up names
        df["Last"] = df["Last"].astype(str).str.strip().str.title()
        df["First"] = df["First"].astype(str).str.strip().str.title()

        # Convert all non-name columns to numeric
        for col in df.columns:
            if col not in ["Last", "First"]:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

        dfs.append(df)

    # Combine all data
    combined = pd.concat(dfs, ignore_index=True)

    # Group by and sum all numeric stats
    agg_df = (
        combined.groupby(["Last", "First"], as_index=False)
        .sum()
    )

    return agg_df

def generate_aggregated_hitting_df(df):
    # Define which columns to keep (inputs)
    cols_to_keep = [
        "Last", "First",
        "PA", "AB", "H", "BB", "HBP", "SF",
        "TB", "R", "RBI", "SO",
        "2B", "3B", "HR", "SB", "CS",
        "QAB", "HHB",
        "LD", "FB", "GB",
        "H_RISP", "AB_RISP",
        "PS", "2OUTRBI", "XBH"
    ]

    # Keep only the relevant columns
    # Ensure all cols_to_keep are in the dataframe, fill missing with 0
    for col in cols_to_keep:
        if col not in df.columns:
            df[col] = 0

    df = df[cols_to_keep].copy()


    # Convert numeric columns
    for col in df.columns:
        if col not in ["Last", "First"]:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    # Aggregate by player
    agg_df = df.groupby(["Last", "First"], as_index=False).sum()

    # Derived stats
    agg_df["AVG"] = np.where(agg_df["AB"] > 0, agg_df["H"] / agg_df["AB"], 0)
    agg_df["OBP"] = np.where(
        (agg_df["AB"] + agg_df["BB"] + agg_df["HBP"] + agg_df["SF"]) > 0,
        (agg_df["H"] + agg_df["BB"] + agg_df["HBP"]) / (agg_df["AB"] + agg_df["BB"] + agg_df["HBP"] + agg_df["SF"]),
        0
    )
    agg_df["SLG"] = np.where(agg_df["AB"] > 0, agg_df["TB"] / agg_df["AB"], 0)
    agg_df["OPS"] = agg_df["OBP"] + agg_df["SLG"]

    agg_df["QAB%"] = np.where(agg_df["PA"] > 0, agg_df["QAB"] / agg_df["PA"], 0)
    agg_df["BB/K"] = np.where(agg_df["SO"] > 0, agg_df["BB"] / agg_df["SO"], agg_df["BB"])
    agg_df["C%"] = np.where(agg_df["AB"] > 0, 1 - (agg_df["SO"] / agg_df["AB"]), 0)
    agg_df["HHB%"] = np.where(agg_df["AB"] > 0, agg_df["HHB"] / agg_df["AB"], 0)

    total_batted = agg_df["LD"] + agg_df["FB"] + agg_df["GB"]
    agg_df["LD%"] = np.where(total_batted > 0, agg_df["LD"] / total_batted, 0)
    agg_df["FB%"] = np.where(total_batted > 0, agg_df["FB"] / total_batted, 0)
    agg_df["GB%"] = np.where(total_batted > 0, agg_df["GB"] / total_batted, 0)

    # BABIP = (H - HR) / (AB - SO - HR + SF)
    denom = agg_df["AB"] - agg_df["SO"] - agg_df["HR"] + agg_df["SF"]
    agg_df["BABIP"] = np.where(denom > 0, (agg_df["H"] - agg_df["HR"]) / denom, 0)

    agg_df["BA/RISP"] = np.where(agg_df["AB_RISP"] > 0, agg_df["H_RISP"] / agg_df["AB_RISP"], 0)
    agg_df["PS/PA"] = np.where(agg_df["PA"] > 0, agg_df["PS"] / agg_df["PA"], 0)

     # Round all decimal-based columns to 3 places
    pct_cols = [
        "AVG", "OBP", "SLG", "OPS", "QAB%", "BB/K", "C%", "HHB%",
        "LD%", "FB%", "GB%", "BABIP", "BA/RISP", "PS/PA"
    ]
    agg_df[pct_cols] = agg_df[pct_cols].round(3)

    # Final column order (as you specified)
    final_cols = [
        "Last", "First",
        "PA", "AB", "AVG", "OBP", "OPS", "SLG", "H", "R", "RBI", "BB",
        "2B", "SB", "QAB", "QAB%", "BB/K", "C%", "HHB", "HHB%", "LD%", "FB%", "GB%",
        "BABIP", "BA/RISP", "2OUTRBI", "XBH", "TB", "PS/PA", "SO"
    ]

    # Some of those may not exist, so keep only present ones
    agg_df = agg_df[[c for c in final_cols if c in agg_df.columns]]

    return agg_df

hitting_df = aggregate_stats_hitting(["wake","unc"])
hitting_df = generate_aggregated_hitting_df(hitting_df)
hitting_df = prepare_batting_stats(hitting_df)
hitting_df.tail()

"""# Aggregation (Fielding)"""

def aggregate_stats_fielding(csv_files):
    # Base numeric columns needed for calculations
    cols_to_keep = ["TC", "A", "PO", "E", "DP"]

    dfs = []
    for name in csv_files:
        file = f"{name}.csv"
        try:
            df = pd.read_csv(file, header=1)  # use header=1 only if CSV has two header lines
            # Adjust the range to include all columns from 148 onwards
            df = df.iloc[:, [1, 2] + list(range(148, df.shape[1]))]
            df.columns = [c.replace(".1", "") for c in df.columns]

            # Ensure name columns exist and keep only relevant columns
            if 'Last' not in df.columns:
                df['Last'] = ""
            if 'First' not in df.columns:
                df['First'] = ""

            # Keep only relevant columns that exist
            df = df[[c for c in cols_to_keep + ["Last", "First"] if c in df.columns]]

            # Clean names
            df["Last"] = df["Last"].astype(str).str.strip().str.title()
            df["First"] = df["First"].astype(str).str.strip().str.title()

            # Convert numeric columns
            for col in df.columns:
                if col not in ["Last", "First"]:
                    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

            dfs.append(df)

        except FileNotFoundError:
            print(f"Warning: File {file} not found. Skipping.")
            continue
        except Exception as e:
            print(f"Warning: Error processing file {file}: {e}. Skipping.")
            continue

    # ===== Combine and aggregate by player =====
    if not dfs:
        return pd.DataFrame(columns=cols_to_keep + ["Last", "First", "Plays Made"])

    combined = pd.concat(dfs, ignore_index=True)

    # Group by player and sum all numeric values
    agg_df = (
        combined.groupby(["Last", "First"], as_index=False)
        .sum(numeric_only=True)
    )

    # Convert numeric columns and handle NaNs
    for col in agg_df.columns:
        if col not in ["Last", "First"]:
            agg_df[col] = agg_df[col].fillna(0).round(3)


    agg_df["FPCT"] = ((agg_df["A"] + agg_df["PO"]) / agg_df["TC"]).round(3).fillna(0)

    return agg_df

fielding_df = aggregate_stats_fielding(["wake","unc"])
fielding_df = prepare_fielding_stats(fielding_df)
fielding_df.head()

"""# Aggregation (Catching)"""

def aggregate_stats_catching(csv_files):
    # Base numeric columns needed for calculations
    cols_to_keep = ["INN", "PB", "SB", "SB-ATT", "CS"]

    dfs = []
    for name in csv_files:
        file = f"{name}.csv"
        try:
            df = pd.read_csv(file, header=1)  # use header=1 only if CSV has two header lines
            # Adjust the range to include all columns from 148 onwards
            df = df.iloc[:, [1, 2] + list(range(148, df.shape[1]))]
            df.columns = [c.replace(".1", "") for c in df.columns]
            df.columns = [c.replace(".2", "") for c in df.columns]


            # Ensure name columns exist and keep only relevant columns
            if 'Last' not in df.columns:
                df['Last'] = ""
            if 'First' not in df.columns:
                df['First'] = ""

            # Keep only relevant columns that exist
            df = df[[c for c in cols_to_keep + ["Last", "First"] if c in df.columns]]

            # Clean names
            df["Last"] = df["Last"].astype(str).str.strip().str.title()
            df["First"] = df["First"].astype(str).str.strip().str.title()

            # Convert numeric columns
            for col in df.columns:
                if col not in ["Last", "First", "SB-ATT"]: # Exclude SB-ATT from initial conversion
                    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

            dfs.append(df)

        except FileNotFoundError:
            print(f"Warning: File {file} not found. Skipping.")
            continue
        except Exception as e:
            print(f"Warning: Error processing file {file}: {e}. Skipping.")
            continue

    # ===== Combine and aggregate by player =====
    if not dfs:
        return pd.DataFrame(columns=cols_to_keep + ["Last", "First"])

    combined = pd.concat(dfs, ignore_index=True)

    # Ensure "SB-ATT" column exists before splitting
    if "SB-ATT" in combined.columns:
        # Split "SB-ATT" into "SB" and "ATT", handling cases without a hyphen
        split_sb_att = combined["SB-ATT"].astype(str).str.split("-", expand=True)
        if split_sb_att.shape[1] < 2:
             # If expand=True didn't create two columns, add a second NaN column
             split_sb_att[1] = np.nan

        combined["SB"] = pd.to_numeric(split_sb_att[0], errors="coerce").fillna(0).astype(int)
        combined["ATT"] = pd.to_numeric(split_sb_att[1], errors="coerce").fillna(0).astype(int)
    else:
        # Add SB and ATT columns with default 0 if SB-ATT is not present
        combined["SB"] = 0
        combined["ATT"] = 0


    # Group by player and sum all numeric values
    agg_df = (
        combined.groupby(["Last", "First"], as_index=False)
        .sum(numeric_only=True)
    )


    # Convert numeric columns and handle NaNs
    for col in agg_df.columns:
        if col not in ["Last", "First", "INN"]:
            agg_df[col] = agg_df[col].fillna(0).round(0)

    agg_df["CS%"] = np.where(
        agg_df["ATT"] > 0,
        (agg_df["CS"] / agg_df["ATT"] * 100).round(1),
        0
    )
    agg_df["SB-ATT"] = agg_df["SB"].astype(int).astype(str) + "-" + agg_df["ATT"].astype(int).astype(str)
    agg_df = agg_df.drop(columns=["SB", "ATT"])

    return agg_df

catching_df = aggregate_stats_catching(["wake","jmu","unc"])
catching_df = prepare_catching_stats(clean_df(catching_df))
catching_df.head()

"""# DFs"""

fielding_df = prepare_fielding_stats(clean_df(pd.read_csv("cumulative.csv", header=1)))
fielding_df.head()

hitting_df = prepare_batting_stats(clean_df(pd.read_csv("cumulative.csv", header=1)))
hitting_df.tail()

pitching_df = prepare_pitching_stats(clean_df(pd.read_csv("cumulative.csv", header=1)))
pitching_df.head()

catching_df = prepare_catching_stats(pd.read_csv("cumulative.csv", header=1))
#catching_df.head()

#user selects stat type, name (one, multiple, or all), series (can select multiple).
# the output is either from cumulative df or pulls from different series dfs

# create a function with logic to create a total line, must hard code math. can be used for all dfs

"""# STAT EXPLANATION"""

data = {
    "Acronym": [
        "PA", "AB", "H", "AVG", "OBP", "SLG", "OPS", "RBI", "R",
        "BB", "SO", "XBH", "2B", "3B", "HR", "TB", "SB",
        "PS/PA", "BB/K", "C%",
        "QAB", "QAB%", "HHB", "HHB %",
        "LD%", "FB%", "GB%",
        "BABIP", "BA/RISP", "2OUTRBI"
    ],
    "Meaning": [
        "Plate Appearances",
        "At-Bats",
        "Hits",
        "Batting Average",
        "On-Base Percentage",
        "Slugging Percentage",
        "On-base Plus Slugging",
        "Runs Batted In",
        "Runs Scored",
        "Walks (Base on Balls)",
        "Strikeouts",
        "Extra-Base Hits",
        "Doubles",
        "Triples",
        "Home Runs",
        "Total Bases",
        "Stolen Bases",
        "Pitches per Plate Appearance",
        "Walk-to-Strikeout Ratio",
        "Contact Percentage",
        "Quality At-Bats",
        "Quality At-Bat Percentage",
        "Hard-Hit Balls",
        "Hard-Hit Ball Percentage",
        "Line Drive Percentage",
        "Fly Ball Percentage",
        "Ground Ball Percentage",
        "Batting Average on Balls In Play",
        "Batting Average with Runners in Scoring Position",
        "Two-Out Runs Batted In"
    ]
}

acronym_df = pd.DataFrame(data)
acronym_df

data = {
    "Acronym": [
        "IP", "ERA", "WHIP", "H", "R", "ER", "BB", "BB/INN", "SO", "K-L", "HR",
        "S%", "FPS%", "FPSO%", "FPSH%", "SM%", "<3%",
        "LD%", "FB%", "GB%", "HHB%", "WEAK%", "BBS",
        "BAA", "BABIP", "BA/RISP",
        "CS", "SB", "SB%",
        "FIP"
    ],
    "Meaning": [
        "Innings Pitched",
        "Earned Run Average",
        "Walks plus Hits per Inning Pitched",
        "Hits Allowed",
        "Runs Allowed",
        "Earned Runs",
        "Walks (Base on Balls)",
        "Walks per Inning",
        "Strikeouts",
        "Strikeouts Looking",
        "Home Runs Allowed",
        "Strike Percentage",
        "First-Pitch Strike Percentage",
        "% of FPS ABs that end in outs",
        "% of FPS that are hits",
        "Swinging Miss Percentage",
        "% of ABs with 3 or fewer pitches",
        "Line Drive Percentage",
        "Fly Ball Percentage",
        "Ground Ball Percentage",
        "Hard-Hit Ball Percentage",
        "Weak Contact Percentage",
        "Base on Balls that results in a run",
        "Batting Average Against",
        "Batting Average on Balls In Play",
        "Batting Average with Runners in Scoring Position",
        "Caught Stealing",
        "Stolen Bases Allowed",
        "Stolen Base Percentage",
        "Fielding Independent Pitching"
    ]
}

pitching_acronyms_df = pd.DataFrame(data)
pitching_acronyms_df

